In [1]:
import tensorflow as tf

# **1. Creating tensors from constants**
*  you can create tensors using the if constant() function.

In [3]:
# creaating a scalar(0D tensors)
scalar = tf.constant(42)
print(scalar)



tf.Tensor(42, shape=(), dtype=int32)


In [4]:
# Creating a vector (1D tensors)
vector = tf.constant([1,2,3,4])
print(vector)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [5]:
#creating a matrix (2D tensors)
matrix = tf.constant([[1,2],[3,4]])
print(matrix)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [6]:
# Creating a 3 tensor
tensor_3d = tf.constant([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(tensor_3d)

tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)


In [7]:
variable_tensor = tf.Variable([[1.0, 2.0]])

In [8]:
# Creating a tensor filled with zeros
zeros_tensor = tf.zeros((2, 3))

# Creating a tensor fille with ones
ones_tensor = tf.ones((3, 3))

# Creating a tensor filled with a specific value
filled_tensor = tf.fill((2, 2), 9)

print(zeros_tensor)
print(ones_tensor)
print(filled_tensor)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[9 9]
 [9 9]], shape=(2, 2), dtype=int32)


In [9]:
#Creating a sequence from 0 to 9
range_tensor = tf.range(10)

#Creating a sequence of 5 values from 0 to 1
linspace_tensor = tf.linspace(0.0, 1.0, 5)

print(range_tensor)
print(linspace_tensor)

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)
tf.Tensor([0.   0.25 0.5  0.75 1.  ], shape=(5,), dtype=float32)


In [10]:
# Creating a tensor with random values from a normal distribution
random_normal = tf.random.normal((2, 3), mean =0, stddev =1)

# Creating a tensor with random values from a uniform distribution
random_uniform = tf.random.uniform((2, 3), minval =0, maxval=10)

print(random_normal)
print(random_uniform)

tf.Tensor(
[[-0.48474848  0.6115795   3.233186  ]
 [-1.0150135  -2.0102098   0.9389764 ]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[3.8306856  5.1617727  2.0344675 ]
 [0.69508433 1.8554258  4.231392  ]], shape=(2, 3), dtype=float32)


In [11]:
import numpy as np

#Creating a NumPy array
numpy_array = np.array([[1,2,3],[4,5,6]])

# Converting to a TensorFlow tensor
tensor_from_numpy = tf.convert_to_tensor(numpy_array)

print(tensor_from_numpy)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int64)


In [12]:
tensor = tf.constant([[1, 2, 3], [4, 5, 6]])

print("Shape:", tensor.shape)
print("Data type:", tensor.dtype)
print("Rank (Dimensions):", tf.rank(tensor))

Shape: (2, 3)
Data type: <dtype: 'int32'>
Rank (Dimensions): tf.Tensor(2, shape=(), dtype=int32)
